<?php
/**
 * Created by PhpStorm.
 * User: vsposato
 * Date: 4/26/14
 * Time: 5:26 PM
 */

namespace test\Thybag;

chdir(dirname(__FILE__));
require_once('../../SharePointAPI.php');

use Thybag\SharePointAPI;

class SharePointAPITest extends \PHPUnit_Framework_TestCase {

    public static function setUpBeforeClass() {

    }

    protected function setUp() {
        parent::setUp();

        if (file_exists('TestIncludes/SharepointAPI.wsdl')) {
            $sharepointAPI = $this->getMockFromWsdl(
                'TestIncludes/SharepointAPI.wsdl', 'ListsSoap'
            );
            fwrite(STDERR,var_dump($sharepointAPI));
        }


    }

    protected function tearDown() {

    }

    public function testGetLimitedLists() {


        $this->assertTrue(TRUE);
    }

    public function getLimitedListsDataProvider() {
        $getLimitedListsResults1 = <<<XML1
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <GetListCollectionResponse xmlns="http://schemas.microsoft.com/sharepoint/soap/">
            <GetListCollectionResult>
                <Lists>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Announcements/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{C0E168F3-A1BB-46A9-B286-12B0752A542E}" Title="Announcements"
                          Description="Use this list to track upcoming events, status updates or other team news."
                          ImageUrl="/_layouts/images/itann.png" Name="{C0E168F3-A1BB-46A9-B286-12B0752A542E}"
                          BaseType="0" FeatureId="00bfea71-d1ce-42de-9c63-a44004ce0104" ServerTemplate="104"
                          Created="20120508 18:45:32" Modified="20120508 18:45:33" LastDeleted="20120508 18:45:32"
                          Version="0" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="536875008" ItemCount="1" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Calendar/calendar.aspx"
                          MobileDefaultViewUrl="" ID="{747C42FC-A948-431C-85D5-CE6FD082C796}" Title="Calendar"
                          Description="Use the Calendar list to keep informed of upcoming meetings, deadlines, and other important events."
                          ImageUrl="/_layouts/images/itevent.png" Name="{747C42FC-A948-431C-85D5-CE6FD082C796}"
                          BaseType="0" FeatureId="00bfea71-ec85-4903-972d-ebe475780106" ServerTemplate="106"
                          Created="20120508 18:45:32" Modified="20140507 12:08:50" LastDeleted="20140330 19:55:50"
                          Version="0" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="541069312" ItemCount="173" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/DIAB143/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{2F044AC3-56DC-4F1B-B755-1FCB84E240E5}" Title="DIAB-143"
                          Description="DIAB-143" ImageUrl="/_layouts/images/itgen.png"
                          Name="{2F044AC3-56DC-4F1B-B755-1FCB84E240E5}" BaseType="0"
                          FeatureId="00bfea71-de22-43b2-a848-c05709900100" ServerTemplate="100"
                          Created="20131119 13:51:35" Modified="20140301 06:03:45" LastDeleted="20131119 13:51:35"
                          Version="12" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="545263616" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="5498" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Documents/Forms/template.dotx"
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Documents/Forms/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{97ABFD82-6F32-4DA4-8D5D-37D0870F629D}" Title="Documents"
                          Description="This system library was created by the Publishing feature to store documents that are used on pages in this site."
                          ImageUrl="/_layouts/images/itdl.png" Name="{97ABFD82-6F32-4DA4-8D5D-37D0870F629D}"
                          BaseType="1" FeatureId="00bfea71-e717-4e80-aa17-d0c71b360101" ServerTemplate="101"
                          Created="20120508 18:46:23" Modified="20140418 02:24:02" LastDeleted="20120508 18:46:23"
                          Version="13" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="8392844" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="False"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/EpicTraining/Forms/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{D05235CC-7B12-4638-BD43-D1D6519FCB53}" Title="EpicTraining"
                          Description="" ImageUrl="/_layouts/images/ital.png"
                          Name="{D05235CC-7B12-4638-BD43-D1D6519FCB53}" BaseType="1"
                          FeatureId="4bcccd62-dcaf-46dc-a7d4-e38277ef33f4" ServerTemplate="851"
                          Created="20140422 15:46:29" Modified="20140422 15:52:39" LastDeleted="20140422 15:46:29"
                          Version="7" Direction="none" ThumbnailSize="128" WebImageWidth="320" WebImageHeight="320"
                          Flags="29364232" ItemCount="32" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="22" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl="" DefaultViewUrl="" MobileDefaultViewUrl=""
                          ID="{89978646-767B-4B52-AE6A-3F1A0C63A3C5}" Title="fpdatasources" Description=""
                          ImageUrl="/_layouts/images/itdl.png" Name="{89978646-767B-4B52-AE6A-3F1A0C63A3C5}"
                          BaseType="1" FeatureId="00bfea71-f381-423d-b9d1-da7a54c50110" ServerTemplate="110"
                          Created="20121023 14:00:43" Modified="20121023 14:00:43" LastDeleted="20121023 14:00:43"
                          Version="0" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="135432" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="22" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="True" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/PublishingImages/Forms/Thumbnails.aspx"
                          MobileDefaultViewUrl="" ID="{A24E8A1C-CEA2-455C-888E-0E8201EC3FC8}" Title="Images"
                          Description="This system library was created by the Publishing feature to store images that are used on pages in this site."
                          ImageUrl="/_layouts/images/ital.png" Name="{A24E8A1C-CEA2-455C-888E-0E8201EC3FC8}"
                          BaseType="1" FeatureId="4bcccd62-dcaf-46dc-a7d4-e38277ef33f4" ServerTemplate="851"
                          Created="20120508 18:46:22" Modified="20140418 02:24:02" LastDeleted="20120508 18:46:22"
                          Version="13" Direction="none" ThumbnailSize="128" WebImageWidth="320" WebImageHeight="320"
                          Flags="29364364" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="False"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Links/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{99B1A739-3CF2-42A6-81BD-7E258678E12D}" Title="Links"
                          Description="Use the Links list for links to Web pages that your team members will find interesting or useful."
                          ImageUrl="/_layouts/images/itlink.png" Name="{99B1A739-3CF2-42A6-81BD-7E258678E12D}"
                          BaseType="0" FeatureId="00bfea71-2062-426c-90bf-714c59600103" ServerTemplate="103"
                          Created="20120508 18:45:32" Modified="20120508 18:45:32" LastDeleted="20120508 18:45:32"
                          Version="0" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight="" Flags="4105"
                          ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1" WriteSecurity="1"
                          Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData="" EmailAlias=""
                          WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="True" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/_catalogs/masterpage/Forms/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{1700ADBB-D42D-4D2F-8ABC-BAE08F65B935}"
                          Title="Master Page Gallery"
                          Description="Use the master page gallery to store master pages. The master pages in this gallery are available to this site and any sites underneath it."
                          ImageUrl="/_layouts/images/itdl.png" Name="{1700ADBB-D42D-4D2F-8ABC-BAE08F65B935}"
                          BaseType="1" FeatureId="" ServerTemplate="116" Created="20120508 18:45:29"
                          Modified="20140418 02:24:02" LastDeleted="20120508 18:45:29" Version="5" Direction="none"
                          ThumbnailSize="" WebImageWidth="" WebImageHeight="" Flags="41947548" ItemCount="3"
                          AnonymousPermMask="0" RootFolder="" ReadSecurity="1" WriteSecurity="1" Author="12"
                          EventSinkAssembly="" EventSinkClass="" EventSinkData="" EmailAlias=""
                          WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="False"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="True" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="True" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Pages/Forms/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{B62E6D80-C78B-4094-A024-4BD3618C095A}" Title="Pages"
                          Description="This system library was created by the Publishing feature to store pages that are created in this site."
                          ImageUrl="/_layouts/images/itdl.png" Name="{B62E6D80-C78B-4094-A024-4BD3618C095A}"
                          BaseType="1" FeatureId="22a9ef51-737b-4ff2-9346-694633fe4416" ServerTemplate="850"
                          Created="20120508 18:46:20" Modified="20140418 02:24:02" LastDeleted="20120508 18:46:21"
                          Version="41" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="148639884" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="False"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="True" RequireCheckout="True" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Phone Call Memo/CallToMe.aspx"
                          MobileDefaultViewUrl="" ID="{649BFE16-79BF-404A-8C6A-F4C12AAFAAB2}" Title="Phone Call Memo"
                          Description="Use this list to share the incoming phone call information."
                          ImageUrl="/_layouts/images/itgbcall.gif" Name="{649BFE16-79BF-404A-8C6A-F4C12AAFAAB2}"
                          BaseType="0" FeatureId="239650e3-ee0b-44a0-a22a-48292402b8d8" ServerTemplate="404"
                          Created="20120508 18:46:50" Modified="20120508 18:46:50" LastDeleted="20120508 18:46:50"
                          Version="0" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="541069440" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Releases/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{57412323-9125-4927-8561-AB8D8D855214}" Title="Releases"
                          Description="" ImageUrl="/_layouts/images/ittask.png"
                          Name="{57412323-9125-4927-8561-AB8D8D855214}" BaseType="0"
                          FeatureId="00bfea71-a83e-497e-9ba0-7a5c597d0107" ServerTemplate="107"
                          Created="20121022 17:49:07" Modified="20140224 02:49:31" LastDeleted="20130410 00:19:49"
                          Version="337" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="616566976" ItemCount="91" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="655" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Facilities and Shared Assets/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{2E36BDF2-B823-4244-ABF3-A87B118CC810}" Title="Resources"
                          Description="Use the Resources list to document shared assets, such as cameras and vehicles. Users can reserve and track listed resources in Group Calendar."
                          ImageUrl="/_layouts/images/itgbfaci.gif" Name="{2E36BDF2-B823-4244-ABF3-A87B118CC810}"
                          BaseType="0" FeatureId="58160a6b-4396-4d6e-867c-65381fb5fbc9" ServerTemplate="402"
                          Created="20120508 18:46:49" Modified="20120508 18:46:49" LastDeleted="20120508 18:46:49"
                          Version="0" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="541069312" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Shared Documents/Forms/template.dotx"
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Shared Documents/Forms/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{439DAC85-9338-4F41-96CF-26587D0CAAB9}" Title="Shared Documents"
                          Description="Share a document with the team by adding it to this document library."
                          ImageUrl="/_layouts/images/itdl.png" Name="{439DAC85-9338-4F41-96CF-26587D0CAAB9}"
                          BaseType="1" FeatureId="00bfea71-e717-4e80-aa17-d0c71b360101" ServerTemplate="101"
                          Created="20120508 18:45:31" Modified="20140507 18:26:42" LastDeleted="20140311 16:52:46"
                          Version="13" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="8392712" ItemCount="883" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="ese-internal-sharedocs"
                          WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="51995780-f1da-4856-95e3-bc332b811ae7" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/SiteAssets/Forms/template.doc"
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/SiteAssets/Forms/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{5EAC09D3-A046-4CE3-B22F-AF8FCD2103E0}" Title="Site Assets"
                          Description="Use this library to store files which are included on pages within this site, such as images on Wiki pages."
                          ImageUrl="/_layouts/images/itdl.png" Name="{5EAC09D3-A046-4CE3-B22F-AF8FCD2103E0}"
                          BaseType="1" FeatureId="00bfea71-e717-4e80-aa17-d0c71b360101" ServerTemplate="101"
                          Created="20120508 18:45:30" Modified="20140418 02:24:02" LastDeleted="20120508 18:45:30"
                          Version="6" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="8392712" ItemCount="3" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="True" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/SitePages/Forms/AllPages.aspx"
                          MobileDefaultViewUrl="" ID="{5ABBB911-7148-4462-8DA2-5EE94D11D9C0}" Title="Site Pages"
                          Description="Use this library to create and store pages on this site."
                          ImageUrl="/_layouts/images/itwp.png" Name="{5ABBB911-7148-4462-8DA2-5EE94D11D9C0}"
                          BaseType="1" FeatureId="00bfea71-c796-4402-9f2f-0eb9a6e71b18" ServerTemplate="119"
                          Created="20120508 18:45:30" Modified="20140418 02:24:02" LastDeleted="20120508 18:45:30"
                          Version="5" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="545263752" ItemCount="2" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="True" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Tasks/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{447976C4-CA18-4B42-AC17-F0C9A389A3EC}" Title="Tasks"
                          Description="Use the Tasks list to keep track of work that you or your team needs to complete."
                          ImageUrl="/_layouts/images/ittask.png" Name="{447976C4-CA18-4B42-AC17-F0C9A389A3EC}"
                          BaseType="0" FeatureId="00bfea71-a83e-497e-9ba0-7a5c597d0107" ServerTemplate="107"
                          Created="20120508 18:45:33" Modified="20140224 02:49:50" LastDeleted="20120508 18:45:33"
                          Version="2" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="549457920" ItemCount="2" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Team Discussion/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{997DBB7F-8D37-4B9A-9F96-6ED92F19D42E}" Title="Team Discussion"
                          Description="Use the Team Discussion list to hold newsgroup-style discussions on topics relevant to your team."
                          ImageUrl="/_layouts/images/itdisc.png" Name="{997DBB7F-8D37-4B9A-9F96-6ED92F19D42E}"
                          BaseType="0" FeatureId="00bfea71-6a49-43fa-b535-d15c05500108" ServerTemplate="108"
                          Created="20120508 18:45:31" Modified="20120508 18:45:31" LastDeleted="20120508 18:45:31"
                          Version="0" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="541069312" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="2" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Whereabouts/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{662C9926-093D-481A-8D48-18896A3FDFFA}" Title="Whereabouts"
                          Description="Use this list to quickly and easily track the location of individuals throughout the day."
                          ImageUrl="/_layouts/images/itgbwher.gif" Name="{662C9926-093D-481A-8D48-18896A3FDFFA}"
                          BaseType="0" FeatureId="9c2ef9dc-f733-432e-be1c-2e79957ea27b" ServerTemplate="403"
                          Created="20120508 18:46:50" Modified="20120508 18:46:50" LastDeleted="20120508 18:46:50"
                          Version="0" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="541069312" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/Lists/Workflow History/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{CB08F1AB-EE15-4B7E-B561-EC04A14A8D1D}" Title="Workflow History"
                          Description="History list for workflow." ImageUrl="/_layouts/images/itwfh.png"
                          Name="{CB08F1AB-EE15-4B7E-B561-EC04A14A8D1D}" BaseType="0"
                          FeatureId="00bfea71-4ea5-48d4-a4ad-305cf7030140" ServerTemplate="140"
                          Created="20121022 19:10:23" Modified="20130409 23:55:13" LastDeleted="20121022 19:10:23"
                          Version="3" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="536875272" ItemCount="461" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="655" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="False" HasExternalDataSource="False" Hidden="True" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl=""
                          DefaultViewUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea/WorkflowTasks/AllItems.aspx"
                          MobileDefaultViewUrl="" ID="{ABEAE9EB-0505-4477-BD64-0F65E7158219}" Title="Workflow Tasks"
                          Description="This system library was created by the Publishing feature to store workflow tasks that are created in this site."
                          ImageUrl="/_layouts/images/ittask.png" Name="{ABEAE9EB-0505-4477-BD64-0F65E7158219}"
                          BaseType="0" FeatureId="00bfea71-a83e-497e-9ba0-7a5c597d0107" ServerTemplate="107"
                          Created="20120508 18:46:20" Modified="20140329 11:49:38" LastDeleted="20120508 18:46:20"
                          Version="25" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="683675844" ItemCount="0" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="12" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="False"
                          AllowMultiResponses="False" EnableAttachments="True" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="False" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="False" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                    <List DocTemplateUrl="" DefaultViewUrl="" MobileDefaultViewUrl=""
                          ID="{83A0363C-F15F-4CB2-A999-1178AB99C8B4}" Title="Workflows" Description=""
                          ImageUrl="/_layouts/images/itdl.png" Name="{83A0363C-F15F-4CB2-A999-1178AB99C8B4}"
                          BaseType="1" FeatureId="00bfea71-f600-43f6-a895-40c0de7b0117" ServerTemplate="117"
                          Created="20121023 14:24:14" Modified="20140418 02:24:02" LastDeleted="20121023 14:24:14"
                          Version="5" Direction="none" ThumbnailSize="" WebImageWidth="" WebImageHeight=""
                          Flags="8524168" ItemCount="9" AnonymousPermMask="0" RootFolder="" ReadSecurity="1"
                          WriteSecurity="1" Author="22" EventSinkAssembly="" EventSinkClass="" EventSinkData=""
                          EmailAlias="" WebFullUrl="/wwa/Admin/OCIO/ciodept/SystemsDevelopment/ESE/internalarea"
                          WebId="386ab822-8879-4410-9be5-ac726d0bab31" SendToLocation=""
                          ScopeId="ebe83d87-2be1-47a4-9a2c-4f454f31bb22" MajorVersionLimit="0"
                          MajorWithMinorVersionsLimit="0" WorkFlowId="" HasUniqueScopes="False"
                          NoThrottleListOperations="False" HasRelatedLists="" AllowDeletion="True"
                          AllowMultiResponses="False" EnableAttachments="False" EnableModeration="False"
                          EnableVersioning="True" HasExternalDataSource="False" Hidden="True" MultipleDataList="False"
                          Ordered="False" ShowUser="True" EnablePeopleSelector="False" EnableResourceSelector="False"
                          EnableMinorVersion="False" RequireCheckout="False" ThrottleListOperations="False"
                          ExcludeFromOfflineClient="False" EnableFolderCreation="True" IrmEnabled="False"
                          IsApplicationList="False" PreserveEmptyValues="False" StrictTypeCoercion="False"
                          EnforceDataValidation="False" MaxItemsPerThrottledOperation="20000"/>
                </Lists>
            </GetListCollectionResult>
        </GetListCollectionResponse>
    </soap:Body>
</soap:Envelope>
XML1;

    }
    public static function tearDownAfterClass() {

    }
}
 